from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from src.config import settings
from src.models import Resume, JobListing, JobFit
from pydantic import BaseModel
from typing import List, Optional

# Internal schema without the required raw_text field (LLM can't produce it)
class _ResumeExtracted(BaseModel):
    full_name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    skills: List[str] = []
    experience: List[str] = []
    education: List[str] = []
    projects: List[str] = []

# Internal schema without job_id (we inject the real one after the call)
class _JobFitExtracted(BaseModel):
    score: int
    reasoning: str
    missing_skills: List[str] = []

class Analyzer:
    """
    Wraps LLM calls for Resume Parsing and Job Matching.
    Uses with_structured_output() for reliable JSON from Gemini.
    """
    def __init__(self):
        base_llm = ChatOpenAI(
            model=settings.MODEL_NAME,
            temperature=0.0,
            api_key=settings.OPENAI_API_KEY,
            base_url=settings.OPENAI_API_BASE
        )
        self.resume_llm = base_llm.with_structured_output(_ResumeExtracted)
        self.fit_llm = base_llm.with_structured_output(_JobFitExtracted)

    def structured_resume(self, raw_text: str) -> Resume:
        """
        Extracts structured data from raw resume text.
        """
        prompt = ChatPromptTemplate.from_template(
            """
            Extract structured information from the following resume text.
            If a field is missing, leave it empty or use an empty list.

            RESUME TEXT:
            {text}
            """
        )
        chain = prompt | self.resume_llm
        extracted: _ResumeExtracted = chain.invoke({"text": raw_text})
        # Re-attach raw_text (required by Resume model, not generated by LLM)
        return Resume(
            full_name=extracted.full_name,
            email=extracted.email,
            phone=extracted.phone,
            skills=extracted.skills,
            experience=extracted.experience,
            education=extracted.education,
            projects=extracted.projects,
            raw_text=raw_text,
        )

    def analyze_fit(self, resume: Resume, job: JobListing) -> JobFit:
        """
        Analyzes the fit between a resume and a job description.
        """
        prompt = ChatPromptTemplate.from_template(
            """
            Analyze the fit between the Candidate and the Job.
            Return a score from 0 to 100, reasoning, and missing skills.

            CANDIDATE:
            Skills: {skills}
            Experience: {experience}

            JOB:
            Title: {title}
            Description: {description}
            """
        )
        chain = prompt | self.fit_llm
        extracted: _JobFitExtracted = chain.invoke({
            "skills": ", ".join(resume.skills),
            "experience": "\n".join(resume.experience),
            "title": job.title,
            "description": job.description,
        })
        # Inject the real job_id — LLM shouldn't need to generate this
        return JobFit(
            job_id=job.id,
            score=extracted.score,
            reasoning=extracted.reasoning,
            missing_skills=extracted.missing_skills,
        )
